---

include:
  - project: cri/iac/infrastructure
    file: .gitlab/ci/templates.yml

stages:
  - lint
  - qa

ansible:
  extends: .ansible

black:
  extends: .black

checkov:
  extends: .checkov

yamllint:
  extends: .yamllint
