---

include:
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
  - project: cri/iac/infrastructure
    file: .gitlab/ci/templates.yml

stages:
  - lint
  - test
  - qa

ansible:
  extends: .ansible

black:
  extends: .black

kics-iac-sast:
  needs: []

yamllint:
  extends: .yamllint
