# yamllint disable rule:line-length
---

# roles/backup-restic/tasks/hooks_patcher.yml

- name: Register pre-backup hooks list
  ansible.builtin.set_fact:
    current_backup_pre_hooks: >
      {%- if current_hook.type | d() -%}
        {{ current_backup_pre_hooks + [([ current_backup_path + '/hooks/' + current_hook.cmd[0]] + current_hook.cmd[1:])] }}
      {%- else -%}
        {{ current_backup_pre_hooks + [current_hook.cmd] }}
      {%- endif -%}
  loop: "{{ current_backup.backup_pre_hooks | d([]) }}"
  loop_control:
    loop_var: current_hook

- name: Register post-backup hooks list
  ansible.builtin.set_fact:
    current_backup_post_hooks: >
      {%- if current_hook.type | d() -%}
        {{ current_backup_post_hooks + [([ current_backup_path + '/hooks/' + current_hook.cmd[0]] + current_hook.cmd[1:])] }}
      {%- else -%}
        {{ current_backup_post_hooks + [current_hook.cmd] }}
      {%- endif -%}
  loop: "{{ current_backup.backup_post_hooks | d([]) }}"
  loop_control:
    loop_var: current_hook

- name: Register pre-restore hooks list
  ansible.builtin.set_fact:
    current_backup_restore_pre_hooks: >
      {%- if current_hook.type | d() -%}
        {{ current_backup_restore_pre_hooks + [([ current_backup_path + '/hooks/' + current_hook.cmd[0]] + current_hook.cmd[1:])] }}
      {%- else -%}
        {{ current_backup_restore_pre_hooks + [current_hook.cmd] }}
      {%- endif -%}
  loop: "{{ current_backup.restore_pre_hooks | d([]) }}"
  loop_control:
    loop_var: current_hook

- name: Register post-restore hooks list
  ansible.builtin.set_fact:
    current_backup_restore_post_hooks: >
      {%- if current_hook.type | d() -%}
        {{ current_backup_restore_post_hooks + [([ current_backup_path + '/hooks/' + current_hook.cmd[0]] + current_hook.cmd[1:])] }}
      {%- else -%}
        {{ current_backup_restore_post_hooks + [current_hook.cmd] }}
      {%- endif -%}
  loop: "{{ current_backup.restore_post_hooks | d([]) }}"
  loop_control:
    loop_var: current_hook
