# yamllint disable rule:line-length
---

# roles/backup-restic/tasks/hooks_patcher.yml

- name: Patch hooks list
  ansible.builtin.set_fact:
    "{{ current_hook_patched_list }}": "{% if current_hook.type | d() %}{{ vars[current_hook_patched_list] + [([ current_backup_path + '/hooks/' + current_hook.cmd[0]] + current_hook.cmd[1:])] }}{% else %}{{ vars[current_hook_patched_list] + [current_hook.cmd] }}{% endif %}"
