# yamllint disable rule:line-length
---

# roles/backup-restic/tasks/main.yml

- name: load OS specific variables
  include_vars: "{{ vars_file }}"
  with_first_found:
    - paths:
        - "vars"
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - "defaults.yml"
  loop_control:
    loop_var: vars_file

- name: Ensure srv dir is present
  file:
    path: "{{ backup_srv_path }}"
    state: directory
    owner: root
    group: root
  tags:
    - skip_ansible_lint

- name: Ensure needed dirs are present
  file:
    path: "{{ dir.path }}"
    state: directory
    owner: "{{ dir.owner | d('root') }}"
    group: "{{ dir.group | d('root') }}"
    mode: "{{ dir.mode | d('0600') }}"
  loop:
    - {path: "{{ backup_restic_path }}", mode: "0755"}
    - {path: "{{ backup_restic_path }}/assets", mode: "0755"}
    - {path: "{{ backup_restic_path }}/backups"}
    - {path: "{{ backup_restic_path }}/bin"}
    - {path: "{{ backup_restic_path }}/scripts"}
  loop_control:
    loop_var: dir

- name: Install packages and dependencies
  package:
    name:
      - "{{ pkg_bash_name }}"
      - "{{ pkg_coreutils_name }}"
      - "{{ pkg_curl_name }}"
    state: present

- name: Install desktop dependencies if needed
  include_tasks: "desktop_dependencies.yml"
  when: backup_restic_desktop_host

- name: Install logrotate and configure it
  include_tasks: "logrotate.yml"
  when: backup_restic_logrotate

- name: Get restic bin from Github releases
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ backup_restic_version }}/restic_{{ backup_restic_version }}_linux_amd64.bz2"
    dest: "{{ backup_restic_path }}/bin/restic_{{ backup_restic_version }}.bz2"
    checksum: sha256:https://github.com/restic/restic/releases/download/v{{ backup_restic_version }}/SHA256SUMS

- name: Unarchive restic release
  command:
    cmd: "bzip2 -k -d {{ backup_restic_path }}/bin/restic_{{ backup_restic_version }}.bz2"
    creates: "{{ backup_restic_path }}/bin/restic_{{ backup_restic_version }}"

- name: Grant exec perm to restic bin
  file:
    path: "{{ backup_restic_path }}/bin/restic_{{ backup_restic_version }}"
    owner: root
    group: root
    mode: '0700'

- name: Template restic wrapper scripts
  template:
    src: "srv/restic/{{ item }}.j2"
    dest: "{{ backup_restic_path }}/scripts/{{ item }}"
    owner: root
    group: root
    mode: "0700"
  loop:
    - "cri_alerting.sh"
    - "cri_restic_wrapper.sh"
    - "cri_utils.sh"

- name: Add backups scripts and files
  include_tasks: "backup.yml"
  loop: "{{ backup_restic_list }}"
  loop_control:
    loop_var: current_backup
    label: "{{ current_backup.name }}"
